version: '3'

services:
  web:
    environment:
      - STATIC_FOLDER=static
      - APP_TYPE=HTTP
      - CHUNK_FILE_SIZE_MB=15
      - MAX_FILE_SIZE_MB=25
      - MAX_FILES_SIZE_MB=50
      - APP_URL=http://localhost:8082
      - PORT=8082

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'